### ISSUE TITLE
Find a way to do documentation

### ISSUE THREAD

**Issue by Shubhaankar-Sharma** [Tech-With-Tim/cdn#4]
#### Swagger docs are preferable

**Comment by SnowballSH** [comment]
Personally, I don't think this project is big enough to use swagger docs. We're not expecting everyone to use it with POST requests anyways.
I think a markdown file with bullet points would be fine.

**Comment by Shubhaankar-Sharma** [comment]
Hmmm, 🤷‍♂️  I guess we could just write markdown files...

**Comment by mohamed040406** [comment]
this is finished, isn't it?
